# TensorBoard 指标配置文件
# 定义指标分组、显示名称和记录策略

# 指标分组配置
metric_groups:
  # 核心训练指标 - 最重要的监控指标
  core:
    enabled: true
    description: "核心训练进度指标"
    metrics:
      episode_reward:
        display_name: "Episode_Reward"
        description: "每回合总奖励"
        target: "maximize"
        normal_range: [-5.0, 5.0]
      
      episode_length:
        display_name: "Episode_Length" 
        description: "每回合步数长度"
        target: "optimize"
        normal_range: [10, 200]
      
      success_rate:
        display_name: "Success_Rate"
        description: "回合成功率"
        target: "maximize"
        normal_range: [0.0, 1.0]
      
      current_step:
        display_name: "Current_Step"
        description: "当前训练步数"
        target: "reference"
        normal_range: [0, 10000]

  # 奖励组件详情 - 奖励函数内部分解
  reward:
    enabled: true
    description: "奖励函数组件分解"
    metrics:
      balance_component:
        display_name: "Balance_Component"
        description: "负载平衡奖励组件"
        formula: "exp(-2.0 × CV)"
        target: "maximize"
        normal_range: [0.0, 1.0]
      
      decoupling_component:
        display_name: "Decoupling_Component"
        description: "电气解耦奖励组件"
        formula: "exp(-4.0 × coupling_ratio)"
        target: "maximize"
        normal_range: [0.0, 1.0]
      
      power_component:
        display_name: "Power_Component"
        description: "功率平衡奖励组件"
        formula: "exp(-3.0 × I_normalized)"
        target: "maximize"
        normal_range: [0.0, 1.0]
      
      quality_total:
        display_name: "Quality_Total"
        description: "质量奖励总和"
        formula: "weighted sum of components"
        target: "maximize"
        normal_range: [0.0, 3.0]
      
      final_total:
        display_name: "Final_Total"
        description: "终局奖励总计"
        target: "maximize"
        normal_range: [0.0, 3.0]
      
      threshold_bonus:
        display_name: "Threshold_Bonus"
        description: "阈值奖励加成"
        target: "reference"
        normal_range: [0.0, 1.0]
      
      termination_discount:
        display_name: "Termination_Discount"
        description: "终止条件折扣"
        target: "reference"
        normal_range: [0.5, 1.0]

  # 质量评估指标 - 分区质量评估
  quality:
    enabled: true
    description: "分区质量评估指标"
    metrics:
      unified_quality_score:
        display_name: "Unified_Quality_Score"
        description: "统一质量分数"
        formula: "(1-CV_norm) × (1-coupling_norm) × (1-power_norm)"
        target: "maximize"
        normal_range: [0.0, 1.0]
      
      plateau_confidence:
        display_name: "Plateau_Confidence"
        description: "平台期检测置信度"
        target: "reference"
        normal_range: [0.0, 1.0]

  # 训练算法指标 - PPO算法相关
  training:
    enabled: true
    description: "PPO训练算法指标"
    metrics:
      actor_loss:
        display_name: "Actor_Loss"
        description: "策略网络损失"
        target: "minimize"
        normal_range: [-1.0, 1.0]
      
      critic_loss:
        display_name: "Critic_Loss"
        description: "价值网络损失"
        target: "minimize"
        normal_range: [0.0, 10.0]
      
      policy_entropy:
        display_name: "Policy_Entropy"
        description: "策略熵（探索度）"
        target: "balance"
        normal_range: [0.0, 2.0]

  # 调试诊断信息 - 问题排查用
  debug:
    enabled: false  # 默认关闭，需要时启用
    description: "调试和诊断信息"
    metrics:
      current_reward_mode:
        display_name: "Current_Reward_Mode"
        description: "当前奖励模式标识"
        target: "reference"

# 显示配置
display_settings:
  # 平滑参数
  smoothing: 0.6
  
  # 刷新间隔
  flush_interval: 10  # 每10个episode刷新一次
  
  # 颜色主题
  color_scheme:
    core: "#1f77b4"      # 蓝色
    reward: "#ff7f0e"    # 橙色
    quality: "#2ca02c"   # 绿色
    training: "#d62728"  # 红色
    debug: "#9467bd"     # 紫色

# 警报配置
alerts:
  enabled: true
  thresholds:
    # 奖励异常检测
    reward_anomaly:
      metric: "Core/Episode_Reward"
      condition: "outside_range"
      range: [-10.0, 10.0]
      message: "奖励值异常，可能存在数值不稳定"
    
    # 成功率过低警报
    low_success_rate:
      metric: "Core/Success_Rate"
      condition: "below_threshold"
      threshold: 0.1
      episodes_window: 100
      message: "成功率持续过低，检查训练配置"
    
    # 质量分数停滞警报
    quality_stagnation:
      metric: "Quality/Unified_Quality_Score"
      condition: "no_improvement"
      window: 200
      min_improvement: 0.01
      message: "质量分数长期无改善，可能需要调整策略"

# 导出配置
export_settings:
  # 自动导出间隔（回合数）
  auto_export_interval: 500
  
  # 导出格式
  formats: ["csv", "json"]
  
  # 导出路径
  export_path: "data/tensorboard_exports"
  
  # 包含的指标组
  include_groups: ["core", "reward", "quality"]
